Validate you don't have OPTIONS when cors=True
You'll get an error message from API gateway about a conflict
exception which isn't that helpful.  By adding it to the
validation step here, we get a much clearer error message:

```
ValueError: Route entry cannot have both cors=True and
methods=['OPTIONS', ...] configured.  When CORS is enabled, an OPTIONS
method is automatically added for you.  Please remove 'OPTIONS' from the
list of configured HTTP methods for: /badview
```

Closes #142.