Get pylint working with py37
I needed to upgrade to pylint >= 2, as
the old pylint does not work on python 3.7.
You'll get an error of:

```
...
File "astroid/decorators.py", line 138, in raise_if_nothing_inferred
  yield next(generator)

RuntimeError: generator raised StopIteration
```

However ugprade from pylint 1.x to 2.x introduced new linting issues
I had to fix.  In most cases I opted to keep our existing standards
and disable any new checks that were failing.  These were primarily
refactoring warnings:

R0205: Class 'BaseType' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)
R1705: Unnecessary "elif" after "return" (no-else-return)
R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)

The only slightly invasive change is renaming all the mypy custom types
we use from `UPPER_SNAKE` to `CamelCase` types.